option(TIDE_ENABLE_ASAN "Enable AddressSanitizer" OFF)
option(TIDE_ENABLE_UBSAN "Enable UndefinedBehaviorSanitizer" OFF)
option(TIDE_ENABLE_TSAN "Enable ThreadSanitizer" OFF)
option(TIDE_ENABLE_COVERAGE "Enable coverage instrumentation" OFF)

function(tide_append_sanitizers target)
  if(MSVC)
    return()
  endif()

  set(flags "")
  if(TIDE_ENABLE_ASAN)
    list(APPEND flags address)
  endif()
  if(TIDE_ENABLE_UBSAN)
    list(APPEND flags undefined)
  endif()
  if(TIDE_ENABLE_TSAN)
    if(WIN32)
      if(NOT TIDE_TSAN_UNSUPPORTED_WARNING_EMITTED)
        message(WARNING "ThreadSanitizer is not supported by this Windows Clang target; TSan flags will not be added.")
        set(TIDE_TSAN_UNSUPPORTED_WARNING_EMITTED ON CACHE INTERNAL "TSan unsupported warning emitted")
      endif()
    else()
      list(APPEND flags thread)
    endif()
  endif()

  if(flags)
    string(REPLACE ";" "," sanitizer_list "${flags}")
    target_compile_options(${target} PRIVATE -fsanitize=${sanitizer_list} -fno-omit-frame-pointer)
    target_link_options(${target} PRIVATE -fsanitize=${sanitizer_list})
  endif()

  if(TIDE_ENABLE_COVERAGE)
    target_compile_options(${target} PRIVATE --coverage -O0)
    target_link_options(${target} PRIVATE --coverage)
  endif()
endfunction()
